### ISSUE TITLE
error CS0103: The name `directory' does not exist in the current context

### ISSUE THREAD

**Issue by almorak** [hiramtan/HiAssetBundle_unity#1]
it comes up this error during the building process (android)
Assets/Script/Core/AssetBundle/AssetBundleUtility.cs(43,20): error CS0103: The name `directory' does not exist in the current context

**Comment by almorak** [comment]
it works fine in the following replacement:

        public static string GetManifestPath()
        {
			string directory = "";
        #if UNITY_EDITOR
            directory = GetAssetBundleFolder() + "/" +
                GetPlatformName(EditorUserBuildSettings.activeBuildTarget);
        #else
            directory = GetAssetBundleFolder() + "/" +
                GetPlatformName(Application.platform);
        #endif
            return directory;
        }

**Comment by hiram3512** [comment]
Thanks for your feedback, yes there is a unnamed variable in content. The corrected logic have already be submitted.
