### ISSUE TITLE
支持新版Unity?

### ISSUE THREAD

**Issue by optimisez** [hiramtan/HiAssetBundle_unity#2]
请问下能不能把工程升级目前最新的Unity 2017.3.1版本然后把旧的API都更新一下?  目前我用那版本打开工程修改了下错误但Example场景无法运行。估计是有些API无法很好地兼容这个新版本。

**Comment by hiram3512** [comment]
我现在用的2018版本,每个平台unity API会有一些不同,欢迎添加平台宏贡献代码.
